### ISSUE TITLE
Remove broken link to deprecated link package and document linkTo usage

### ISSUE THREAD

**Issue by gvaldambrini** [storybooks/storybooks.github.io#10]
The link in the addon gallery is broken, and I was not able to find the right link (the repo [here](https://github.com/storybooks/storybook-addon-links) is marked as deprecated)

**Comment by shilman** [comment]
@gvaldambrini `linkTo` is now built into storybook. So I'm going to remove the broken link since it's no longer an addon, and add documentation on how to use links.

**Comment by shilman** [comment]
Fixed and updated. There is still a follow-on issue here: https://github.com/storybooks/storybook/issues/966

**Comment by shilman** [comment]
NOTE: I got this completely wrong. See https://github.com/storybooks/storybook/issues/1016
