### ISSUE TITLE
ADD search

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybooks.github.io#46]
Finding something in the documentation is hard right now.

We need to create something that will allow users to type in a query and we'll display a list of page / segments.

**Comment by shilman** [comment]
AFAIK most static sites use an external search engine service like Lunr, Algolia, Google, etc.:
- https://github.com/slashdotdash/jekyll-lunr-js-search
- https://github.com/PascalW/jekyll_indextank
- https://www.npmjs.com/package/hexo-algolia
- https://cse.google.com/cse/

**Comment by ndelangen** [comment]
If you can do react-router, you surely can do some client-size fuzzy search?

**Comment by ndelangen** [comment]
I'm going to move this issue over.
