### ISSUE TITLE
Favicon is not showing

### ISSUE THREAD

**Issue by ndelangen** [storybooks/storybooks.github.io#47]

**Comment by usulpro** [comment]
doesn't we already have one?

**Comment by ndelangen** [comment]
It's not showing

**Comment by usulpro** [comment]
what browser do you use?
It works fine in Chome and Firefox, but not in IE.

**Comment by ndelangen** [comment]
I'm blind

**Comment by usulpro** [comment]
Maybe we should fix it for IE @shilman ?
