### ISSUE TITLE
Direct URL support

### ISSUE THREAD

**Issue by arunoda** [storybooks/storybooks.github.io#5]
Hey guys,

Since this is a SPA, direct urls like https://storybooks.js.org/docs won't work with GitHub.
Here's a detailed discussion on this: https://github.com/isaacs/github/issues/408

So, it might be a good idea to move this heroku / firebase hosting / Zeit now or similar.

**Comment by arunoda** [comment]
Let's keep this open until we found a proper fix right?

**Comment by shilman** [comment]
@mnmtanish do you know if these other solutions (heroku / zeit / etc.) are valid for `js.org` domains?

**Comment by thani-sh** [comment]
Unfortunately we can use `.js.org` domains only with GIthub pages.

The webpack.js.org site is generating separate html files for each URL ( [example](https://github.com/webpack/webpack.js.org/tree/e418f4a504129246e0495e629499761e148ce339/concepts) ). We should check that site source to see if there's a way to do this automatically.

**Comment by shilman** [comment]
Closing now that the Gatsby PR is merged. Please file issues with the new site separately!
