### ISSUE TITLE
Improve addons gallery section

### ISSUE THREAD

**Issue by usulpro** [storybooks/storybooks.github.io#51]
How do you like the idea to add some features/improvements to this section?

At this moment it has only the Title, link to the repo and short description.
We could add:

- Live demo links (if exists)

- Info of what kind of addon it is (panel, stories-API extension, decorator)

- Author name + avatar

- Screenshots

We could collect statistic of clicks. The simplest way is to use a service like https://bitly.com/ Maybe you have better ideas for that? I think we need this just because of interest what people likes more/less, what traffic we can generate. 

We can create logo/badge of `storybook addon` for addon developers to put it on their readme pages and point to the addon gallery item.

I think we need to reorder this list as well. But how? Alphabetically? 

Your thoughts?

**Comment by shilman** [comment]
@UsulPro working on something related in #45 . Sync with me if you're going to work on this one.
