### ISSUE TITLE
Homepage refresh

### ISSUE THREAD

**Issue by shilman** [storybooks/storybooks.github.io#56]
### why

- more useful info for first-time visitors
- more social proof
- better look and feel

### what
- [x] logos of companies using storybooks
- [ ] better layout
- [x] logo refresh TBD storybooks/storybook#1100 
- [ ] video content TBD

**Comment by ndelangen** [comment]
Wanna move this issue over? Might be easier by hand I guess.

**Comment by shilman** [comment]
@ndelangen gonna close this for now. i'll create issues as i'm ready to actually work on them.
