### ISSUE TITLE
New tagline

### ISSUE THREAD

**Issue by SachaG** [storybooks/storybooks.github.io#66]
"The UI Development Environment you'll [heart] to use" isn't very descriptive. Also, that heart icon randomly disappears for me sometimes so I just see an empty box. 

How about: 

> The UI component explorer, for React & React Native

> Build & maintain your own component libraries, for React & React Native

> Component-driven development doesn't have to be a fairy tale anymore (j/k)

**Comment by shilman** [comment]
@SachaG we have moved the docs over to `@storybooks/storybook` to:
- stay in sync with rest of codebase
- move the domain of the docs

See also #64 . We'll merge that when we do the 3.0 release and complete the transition. In the meantime, we should only make critical changes to this repo.
