### ISSUE TITLE
`EDIT THIS PAGE` Doc Links are Broken

### ISSUE THREAD

**Issue by danny-andrews** [storybooks/storybooks.github.io#7]
Various docs links are broken. Looks like master doesn't have current files?

**STR:**
Go to: https://storybooks.js.org/docs/react-storybook/configurations/custom-webpack-config
Click `EDIT THIS PAGE` link.
**Expected:**
Takes me to file to edit that page
**Actual:**
Takes me to GitHub 404 page

**Comment by xavxyz** [comment]
Thanks for raising this issue @danny-andrews, it got fixed 🙆‍♂️
